import { useMemo, useState } from "react";
import { createRoot } from "react-dom/client";
import { AlertTriangle, ArrowUpRight, CheckCircle2, Copy, ExternalLink, Search, ShieldAlert, ShieldCheck, Wallet } from "lucide-react";
import "./styles.css";
type Risk = "high" | "medium" | "low";
type Tx = { hash:string; title:string; method:string; token:string; amount:string; from:string; to:string; risk:Risk; summary:string; details:string[]; gas:string; time:string };
const samples:Tx[]=[
 {hash:"0x8f2a...91cd",title:"USDT 무제한 사용 권한 승인",method:"approve(address,uint256)",token:"USDT",amount:"무제한",from:"0x71C...A91",to:"0x9b4...E02",risk:"high",summary:"수신 컨트랙트가 지갑의 USDT를 제한 없이 사용할 수 있습니다.",details:["자산 이동: 현재 즉시 이동은 없음","권한 부여: USDT 무제한 사용 승인","주의: 승인 후 별도 거래로 잔액을 가져갈 수 있음"],gas:"$0.42",time:"방금 전"},
 {hash:"0x4bc1...0aa7",title:"ETH 전송",method:"native transfer",token:"ETH",amount:"0.12 ETH",from:"0x71C...A91",to:"0x44e...18B",risk:"low",summary:"지정한 주소로 0.12 ETH를 한 번 전송합니다.",details:["자산 이동: 0.12 ETH 전송","권한 부여: 없음","수신 주소의 과거 위험 신호: 발견되지 않음"],gas:"$0.18",time:"3분 전"},
 {hash:"0xa11e...7d2f",title:"NFT 컬렉션 전체 권한 승인",method:"setApprovalForAll(address,bool)",token:"NFT",amount:"전체 컬렉션",from:"0x71C...A91",to:"0x2d1...C77",risk:"medium",summary:"컨트랙트가 해당 컬렉션의 NFT를 대신 전송할 수 있습니다.",details:["자산 이동: 현재 이동 없음","권한 부여: 컬렉션 내 모든 NFT 전송 권한","주의: 사용 후 권한 철회 권장"],gas:"$0.27",time:"어제"}
];
const riskLabel:Record<Risk,string>={high:"높은 위험",medium:"주의 필요",low:"낮은 위험"};
function App(){
 const [query,setQuery]=useState(""); const [selected,setSelected]=useState<Tx|null>(samples[0]); const [copied,setCopied]=useState(false); const [beginnerMode,setBeginnerMode]=useState(true);
 const result=useMemo(()=>query.trim()?samples.find(x=>x.hash.toLowerCase().includes(query.trim().toLowerCase()))??null:selected,[query,selected]);
 function analyze(e:React.FormEvent){e.preventDefault();setSelected(result??samples[0]);}
 function copyHash(){if(!selected)return;navigator.clipboard?.writeText(selected.hash);setCopied(true);setTimeout(()=>setCopied(false),1400)}
 return <main className="app"><header className="topbar"><div className="brand"><div className="logo"><ShieldCheck size={22}/></div><div><strong>TraceSafe</strong><span>거래 서명 전, 지갑을 지키는 해석기</span></div></div><div className="topActions"><button className={beginnerMode?"modeToggle active":"modeToggle"} onClick={()=>setBeginnerMode(v=>!v)}>{beginnerMode?"초보자 모드":"상세 모드"}</button><div className="network"><span className="dot"/> Ethereum Sepolia <Wallet size={16}/></div></div></header>
 <section className="hero"><p className="eyebrow">TRANSACTION SAFETY CHECK</p><h1>서명하기 전에,<br/><em>무슨 일이 일어나는지</em> 확인하세요.</h1><p className="lead">복잡한 컨트랙트 호출을 사람이 읽을 수 있는 거래 내용과 위험 신호로 바꿔드립니다.</p><form className="searchBox" onSubmit={analyze}><Search size={20}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="트랜잭션 해시 또는 컨트랙트 주소를 입력하세요"/><button type="submit">분석하기</button></form><p className="hint">예시를 눌러 바로 체험해보세요 · 실제 거래를 전송하지 않습니다</p></section>
 {beginnerMode&&<section className="learnStrip"><div className="learnIntro"><span className="learnIcon">?</span><div><strong>처음이라면 이렇게 확인하세요</strong><p>어려운 용어 대신 거래의 결과부터 차근차근 살펴봅니다.</p></div></div><div className="learnSteps"><div><b>01</b><span>무엇을 하나요?</span><small>송금인지 권한인지 확인</small></div><div><b>02</b><span>무엇이 바뀌나요?</span><small>거래 전후 자산 비교</small></div><div><b>03</b><span>직접 결정해요</span><small>실제 거래는 지갑에서</small></div></div><div className="practiceNote"><ShieldCheck size={16}/><span><strong>테스트넷에서 연습 가능</strong><br/>실제 돈 없이 거래 흐름을 익혀보세요.</span></div></section>}
 <section className="content"><aside className="history"><div className="sectionTitle"><span>최근 분석</span><small>3건</small></div>{samples.map(tx=><button className={selected?.hash===tx.hash?"historyItem active":"historyItem"} key={tx.hash} onClick={()=>{setSelected(tx);setQuery("")}}><span className={`riskDot ${tx.risk}`}/><span className="historyText"><strong>{tx.title}</strong><small>{tx.hash} · {tx.time}</small></span><span className="chevron">›</span></button>)}<div className="privacy"><ShieldCheck size={17}/><span><strong>읽기 전용 분석</strong><br/>개인키와 자산에 접근하지 않습니다.</span></div></aside>
 <div className="resultWrap">{result?<><div className="resultHead"><div><p className="eyebrow">ANALYSIS RESULT</p><h2>{result.title}</h2><div className="hash">{result.hash}<button onClick={copyHash}><Copy size={14}/>{copied?"복사됨":"복사"}</button><a href="#" onClick={e=>e.preventDefault()}>Explorer <ExternalLink size={13}/></a></div></div><div className={`riskBadge ${result.risk}`}>{result.risk==="high"?<ShieldAlert size={18}/>:result.risk==="medium"?<AlertTriangle size={18}/>:<CheckCircle2 size={18}/>} {riskLabel[result.risk]}</div></div>
 <div className={`summary ${result.risk}`}><div className="summaryIcon">{result.risk==="low"?<CheckCircle2/>:<AlertTriangle/>}</div><div><strong>{result.risk==="high"?"서명 전 확인이 필요합니다":result.risk==="medium"?"이 거래의 권한 범위를 확인하세요":"특별한 위험 신호가 발견되지 않았습니다"}</strong><p>{result.summary}</p></div></div>
 <div className="card"><div className="cardTitle"><span>거래 내용</span><span className="method">{result.method}</span></div><div className="flow"><div><small>보내는 지갑</small><strong>{result.from}</strong></div><ArrowUpRight size={19}/><div><small>수신 컨트랙트</small><strong>{result.to}</strong></div></div><div className="amount"><span>{result.token}</span><strong>{result.amount}</strong></div><div className="detailGrid">{result.details.map((d,i)=><div key={d}><span className={i===1&&result.risk!=="low"?"detailWarn":"detailOk"}>{i===1&&result.risk!=="low"?<AlertTriangle size={15}/>:<CheckCircle2 size={15}/>}</span>{d}</div>)}</div></div>
 <div className="bottomGrid"><div className="card compact"><div className="cardTitle"><span>예상 네트워크 비용</span></div><strong className="gas">{result.gas}</strong><small>Ethereum Sepolia · 변동 가능</small></div><div className="card compact actionCard"><div><strong>분석 결과가 도움이 됐나요?</strong><small>사용자 피드백은 위험 기준을 개선하는 데 사용됩니다.</small></div><div className="feedback"><button>👍</button><button>👎</button></div></div></div></>:<div className="noResult"><Search size={28}/><h2>분석 결과가 없습니다</h2><p>샘플 거래를 선택하거나 올바른 해시를 입력해보세요.</p></div>}</div></section><footer><span>TraceSafe MVP · 분석 결과는 참고용이며 거래의 안전을 보장하지 않습니다.</span><span>Built for Open Challenge</span></footer></main>;
}
createRoot(document.getElementById("root")!).render(<App/>);
